### ISSUE TITLE
Empty commits cause build failures

### ISSUE THREAD

**Issue by elijahe** [CircleCI-Public/path-filtering-orb#101]
## Orb version:
1.0.0

## What happened:

When using a path-filtering configuration without a single `continue_config.yml` file an empty commit (e.g. `git commit --allow-empty -m "[deploy-test] test deploy"`) causes a build failure. The build fails with the following message:

```
Checking For yq + CURL
Config list ===
.circleci/continue_config.yml
Generated YAML ===
Error: open .circleci/continue_config.yml: no such file or directory

Exited with code exit status 123
```

Sample circleci config which can be used to recreate the issue along with an empty commit:

```yaml
---
version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  generate-config:
    jobs:
      - path-filtering/filter:
          base-revision: << pipeline.git.branch >>
          mapping: |
            be/.* build-be true be/.circleci/config.yml
            fe/.* build-fe true fe/.circleci/config.yml
            .* build-root true .circleci/root_level_config.yml

```

## Expected behavior:

The build should not fail. Ideally, any catch-all path filtering configs (e.g. `.*`) should also run.
