### ISSUE TITLE
Suggestion: Filter without additional params, just next config file

### ISSUE THREAD

**Issue by whawker** [CircleCI-Public/path-filtering-orb#104]
## Describe Request:

Currently `mapping` requires you to pass 3 or 4 values on each line

https://github.com/CircleCI-Public/path-filtering-orb/blob/6fb32db67e538491fdcbe49820c2e8d827bf83d3/src/scripts/create-parameters.py#L59-L64

I don't believe a parameter is always necessary, sometimes you just want to forward to a continuation path, _without_ additional parameters.

That is to say, could support for **2 values only** be added? (i.e. no params), I believe this would be a common use case in mono repos.

## Examples:

```yml
    jobs:
      - path-filtering/filter:
          base-revision: main
          mapping: |
            my-app/.* my-app/.circleci/config.yml
            my-other-app/.* my-other-app/.circleci/config.yml
```

## Supporting Documentation Links:

https://circleci.com/developer/orbs/orb/circleci/path-filtering?version=1.0.0
