### ISSUE TITLE
Allow to set a default branch as the fallback for base revision

### ISSUE THREAD

**Issue by pkawula** [CircleCI-Public/path-filtering-orb#124]
## Describe Request:
In my config I would like to use `base-revision: << pipeline.git.base_revision >>` because of multiple base branches for different environments. However, the base_revision is '' when it's the first push and the I would like to fallback to the default branch.

## Examples:
```
version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.3.0

workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          mapping: |
            src/.* backend true
            frontend/projects/project-1/.* project-1 true
            frontend/projects/project-2/.* project-2 true
            frontend/projects/project-3/.* project-3 true
          base-revision: << pipeline.git.base_revision >>
          base-branch: develop
          config-path: .circleci/continue-config.yml

```
