### ISSUE TITLE
Support loading a workspace

### ISSUE THREAD

**Issue by JamieSinn** [CircleCI-Public/path-filtering-orb#15]
## Describe Request:
We're trying to dynamically generate the continuation config in addition to using the path filtering orb, but because the path filtering orb doesn't use workspaces, we can't build the config in one job, and then have the path filtering job use that same config via workspaces

## Examples:

Ideally we can have a job that has this step:
```
      - persist_to_workspace:
          root: ~/
          paths:
            - project/.circleci/dynamic-config.yml
```

And the orb will load the workspace, allowing us to point the new dynamically generated config to be the one used in continiuation.
