### ISSUE TITLE
No matching jobs causes a build error

### ISSUE THREAD

**Issue by yaningo** [CircleCI-Public/path-filtering-orb#20]
## Orb version:
`0.0.2`

## What happened:

If no job matches the [mapping](https://circleci.com/developer/orbs/orb/circleci/path-filtering#jobs-filter), it'll lead to a build error (`Config Processing Error`) with:
```
#!/bin/sh -eo pipefail
# All Workflows have been filtered from this Pipeline.
# No Jobs have been run.
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false

Exited with code exit status 1
CircleCI received exit code 1
```

## Expected behavior:

The build will simply be skipped with a message indicating the reason (No matching job) rather than generate an error.

## Additional Information:

Maybe the [`finish` command of the the `continuation` orb](https://circleci.com/developer/orbs/orb/circleci/continuation#commands-finish) could be called when no job matches the mapping 🤔

**Comment by h42zhu** [comment]
Looks like this is no longer the behaviour for the latest version of the orb:

https://github.com/CircleCI-Public/path-filtering-orb/blob/main/src/scripts/create-parameters.py#L88

Closing this issue.

**Comment by lucas-bsq** [comment]
@h42zhu I'm getting the same behaviour with orb v0.1.6 (i.e. latest) - are you sure the fix works?
The problem is not so much with the warning message in on CircleCI but in that it leads to GitHub checks not passed.

![image](https://github.com/CircleCI-Public/path-filtering-orb/assets/41055906/0dea4d99-1d4c-4125-a3d6-ed1eb35a4c07)

![image](https://github.com/CircleCI-Public/path-filtering-orb/assets/41055906/2694e01c-6489-464d-b2c7-1f88ecb823a1)

**Comment by yagikota** [comment]
I got the same error when using `circleci/path-filtering@1.0.0`.

config.yml
``` yml
version: 2.1

# enable dynamic config
# https://circleci.com/docs/dynamic-config/
setup: true

orbs:
  # https://circleci.com/developer/orbs/orb/circleci/path-filtering
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  my-workflow:
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: ".circleci/hello-world.yml"
          # mapping need
          mapping: |
            /server.* hello-world true

```

hello-world.yml
```yml
version: 2.1

parameters:
  hello-world:
    type: boolean
    default: false

jobs:
  hello-world-job:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: echo "hello world"


workflows:
  version: 2.1
  hello-world:
    when: << pipeline.parameters.hello-world >>
    jobs:
      - hello-world-job
 ```


Same as @lucas-bsq  ,when running ci without changing `/server` directory, I got `All Workflows have been filtered from this Pipeline. No Jobs have been run.` error.
