### ISSUE TITLE
Ability to run config generation after path mapping

### ISSUE THREAD

**Issue by willm** [CircleCI-Public/path-filtering-orb#25]
## Describe Request:
I would like to be able to use the results of the path mapping as parameters in a script to generate my own continue config. Right now the continue step is called immediately afterwards.

This would be very powerful for monorepos as you could use a fully featured scripting language to generate the right workflows according to project dependencies.

## Examples:

```
version: "2.1"
            orbs:
                path-filtering: circleci/path-filtering@0.0.1
                continuation: circleci/continuation@0.2.0
            workflows:
                generate-config:
                    jobs:
                        - path-filtering/filter:
                            base-revision: main
                            skip_continue: true
                            mapping: |
                                src/.* build-code true
                                doc/.* build-docs true
                        - generate-continue-config
                        # this job would read the parameters file written by path filtering and generate a continue-config.yml
                         - continuation/continue:
                              configuration_path: continue-config.yml
```

**Comment by dsansot-ru** [comment]
You can now (not sure about when the issue was created).

I was playing around and just got something like this working:
```
      - path-filtering/set-parameters:
          base-revision: main
          output-path: /tmp/pipeline-parameters.json
          mapping: |
            src/.* build-code true
            doc/.* build-docs true
      - run:
          name: Generate continue-config.yml file
          command: |
            poetry run gen-config -o /tmp/continue-config.yml /tmp/pipeline-parameters.json
      - continuation/continue:
          parameters: "{}"
          configuration_path: /tmp/continue-config.yml
```
