### ISSUE TITLE
Add support for empty commits

### ISSUE THREAD

**Issue by nicolai86** [CircleCI-Public/path-filtering-orb#31]
## Describe Request:

For daily builds we utilize empty github commits to trigger builds on circleci.

This orb would work wonderful for this if it had the ability to set a number of default parameters, which are passed to the continuation pipeline in case no path mapping matches.

## Examples:

example usage:

```
workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          config-path: .circleci/continue_config.yml
          mapping: |
            a/.* build-a true
            b/.* build-b true
          fallback-parameters: |
            {"build-b": true}
          base-revision: origin/master
```

required code change in `set_parameters.py`:

```
mappings = filter(check_mapping, mappings)
mappings = list(map(convert_mapping, mappings))

# if we have no matching path, use fallback parameters in continuation
if len(mappings) > 0:
  mappings = dict(mappings)
  print('using parameters from path filter {}'.format(json.dumps(mappings)))
else:
  fallback = os.environ.get('FALLBACK_PARAMETERS')
  print('using parameters from fallback {}'.format(fallback))
  mappings = dict(json.loads(fallback))
#
```

now, you can create empty commits which will pass the fallback parameters to the continuation:

```
git commit --allow-empty -m "Daily build"
```
