### ISSUE TITLE
Orb doesn't work for jobs that run with tag filter

### ISSUE THREAD

**Issue by ksrisurapaneni** [CircleCI-Public/path-filtering-orb#4]
## Orb version:

0.0.2

## What happened:

Our workflows work fine when we use the branch filter (main or otherwise). Our prod workflow doesn't depend on file changes, but is triggered when a tag gets created.  Once we started using the path-filtering orb (in config.yml) and put the parameters and code logic in continue-config.yml,  the prod workflow is not getting triggered even on new git releases. 

## Expected behavior:

The prod workspace should run always based on it's filters. But since the code logic is in the same file where parameters have been defined for path-filtering, it seems to not be running. 

## Additional Information:

I also tried creating a dummy parameter and gave it a default value of true. I referenced that parameter in the when condition for the prod workflow. It is still not working.

<img width="1035" alt="Screen Shot 2021-05-12 at 1 43 19 PM" src="https://user-images.githubusercontent.com/56444897/118020493-2114b100-b328-11eb-8ed6-4ac0c351cdf8.png">

Thanks!

**Comment by michael-burt** [comment]
I am having this same issue. Is there a way to force the continuation to occur so that tag workflows run?

**Comment by ksrisurapaneni** [comment]
@michael-burt : I agree, tried everything and finally had to remove this orb. :/

**Comment by michael-burt** [comment]
@ksrisurapaneni I ended up building this orb myself and got it working properly for tagged releases. I PR'd the changes into this repository: https://github.com/CircleCI-Public/path-filtering-orb/pull/5

If that does not get merged, you are welcome to use the public orb I published: `uplight/path-filtering@dev:efbb070`

Here is the associated source code: https://github.com/Uplight-Inc/path-filtering-orb

**Comment by mhsaeedi** [comment]
The same issue here

**Comment by ksrisurapaneni** [comment]
Waiting for official fix as well!

**Comment by KASOGIT** [comment]
The same issue here, the circleci/path-filtering job does not work when triggered from tags:
```
##### config.yaml
      - path-filtering/filter:
          base-revision: staging
          config-path: .circleci/continue-config.yml
          mapping: |
            app/.* deploy-app "staging"
          filters:
            tags:
              only: /^[a-z]+-?([a-z]+)?@[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+/
            branches:
              ignore: /.*/
```
```
###continue
  deploy-app:
    when: << pipeline.parameters.deploy-app >>
    jobs:
      - run-job
```
We had to add a filter tag also on the target workflow:
```
  deploy-app:
    when: << pipeline.parameters.deploy-app >>
    jobs:
      - run-job:
          filters:
            tags:
              only: /^.*$/
            branches:
              ignore: /.*/
```
