### ISSUE TITLE
Mapping values must be quoted if not a boolean

### ISSUE THREAD

**Issue by eddiewebb** [CircleCI-Public/path-filtering-orb#40]
## Orb version:  
0.1.2

## What happened:  
set-parameters step fails reading map with `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

The offending command is the ` convert_mapping(m)` function's use of json.loads against the 3rd value in MAPPING - which only works when its a boolean.
```
 def convert_mapping(m):
                      return [m[1], json.loads(m[2])]
```

## Expected behavior:  
use a tool that can read unquoted strings (valid yaml) or document the caveat that the 3rd value in mapping must be valid JSON.

## Additional Information:  

```
workflows:
  build_deploy:
    jobs: 
      - path-filtering/filter:
          base-revision: master
          config-path: .circleci/continue-config.yml
          mapping: |
            module-a/.* module-a true  # this works
            module-b/.* module-b bananas # this fails
```
It is no hint or debug output as to what is wrong, and at first glance seems identical to the orb's example.

The issue is that the `true` is a boolean and `bananas` is a string, and so in JSON rules **which differ than the yaml we're writing it in** require strings in double-quotes specifically (single quotes will also fail)
