### ISSUE TITLE
git diff must be executed without pathquoting

### ISSUE THREAD

**Issue by hchonan** [CircleCI-Public/path-filtering-orb#42]
## Orb version:

All (confirmed v0.0.3 )

## What happened:
If git changeset path is quoted by git (ex. filepath contains white space charactor) , mapping filter does not work correctly.

On Example configuration below;
```
version: '2.1'
orbs:
  path-filtering: circleci/path-filtering@0.0.1
workflows:
  generate-config:
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/continue-config.yml
          mapping: |
            src/.* build-code true
            doc/.* build-docs true
```

If `doc/some file which git quotes.txt` is changed, `git diff` will outputs changed file path as quoted `"doc/some file which git quotes.txt"` and that output will not match with `doc/.* build-docs true` pattern (pattern is compilled appending `^` and `$`).

It considerd that supress git not to output quoted filepath, or describing `mapping` pattern with assuming quote.

My proposal ( PR #41 ) to appending `-c code.quotepath=false` option to git diff command execution.

## Expected behavior:
Even special ( which default setting of git will quote ) path file is changed, use mapping filter same as regular file.

## Additional Information:
Posted PR #41
