### ISSUE TITLE
get exact names of files which changed

### ISSUE THREAD

**Issue by gterziysky** [CircleCI-Public/path-filtering-orb#56]
## Describe Request:

As of path-filtering orb version 0.1.3, there is no way to access the exact names of the files which got matched by the mapping regex. The matching file names are simply discarded:

- lines 68 and 69 in [src/scripts/create-parameters.py](https://github.com/CircleCI-Public/path-filtering-orb/blob/17c4b25958517efdc7476d0adb8e20eb8e823c85/src/scripts/create-parameters.py#L68);
- also see [section orb-source](https://circleci.com/developer/orbs/orb/circleci/path-filtering#orb-source) on the path-filtering orb's CircleCI page.

I would like to avoid the brute force solution where one would need to specify a separate mapping for every file.

That is because to support such a solution would be difficult. For example, suppose a new file were added or a name change were introduced to an existing file. Then the continue config file pointed to by `config-path` would need to be updated in either case. Furthermore, the need arises to document the update process and teach it to colleagues who would like to make a change, but have not yet seen the project. Finally, imagine you've dozens of files changes in which need to be tracked. This means that the continue config file at `config-path` would grow in size significantly and require more effort to maintain.

## Examples:

One solution that comes to mind is to return the results of the regex in a string parameter. If there are no matches to the regex then the string would be empty and would evaluate to false (as per the CircleCI docs on defining conditional steps [the empty string is falsy](https://circleci.com/docs/reusing-config#defining-conditional-steps)) in the continue config. For example, the [continue config](https://circleci.com/docs/using-dynamic-configuration#continueconfig) could then become:

```yml
parameters:
  run-build-service-1-job:
    type: string
    default: ""
  run-build-service-2-job:
    type: string
    default: ""

# ...
jobs:
  build_svc1:
    docker:
      - image: alpine:3.15
    resource_class: medium
    steps:
      - run: echo "<< pipeline.parameters.run-build-service-1-job >>" > files_that_changed.txt
      # ... 
  build_svc2:
    docker:
      - image: alpine:3.15
    resource_class: medium
    steps:
      - run: echo "<< pipeline.parameters.run-build-service-2-job >>" > files_that_changed.txt
     # ...

workflows:
  version: 2
  workflow_svc1:
    when: << pipeline.parameters.run-build-service-1-job >>
    jobs:
      - build_svc1
  workflow_svc2:
    when: << pipeline.parameters.run-build-service-2-job >>
    jobs:
      - build_svc2

  default_workflow:
    jobs:
      - default
```

In this way the matching file names contained in the respective parameters will be available to the docker container spun up by the continue config.

This could be implemented by modifying lines 62 to 77 in [src/scripts/create-parameters.py](https://github.com/CircleCI-Public/path-filtering-orb/blob/17c4b25958517efdc7476d0adb8e20eb8e823c85/src/scripts/create-parameters.py#L62) in the following way:

```python
def convert_mapping(m):
    if 3 != len(m):
        raise Exception("Invalid mapping")
    path, param, value = m
    regex = re.compile(r'^' + path + r'$')
    match_list = []
    for change in changes:
        re_match = regex.match(change)
        if re_match:
            match_list.append(re_match.group())
    return [param, ";".join(match_list)]

mappings = map(convert_mapping, mappings)
mappings = dict(mappings)
```

## Supporting Documentation Links:

- [path-filtering orb: get names of files which changed](https://discuss.circleci.com/t/path-filtering-orb-get-names-of-files-which-changed/45136)
- [when condition and empty string](https://discuss.circleci.com/t/problem-with-when-condition-and-empty-string/28375/2)
- [path-filtering orb source code](https://circleci.com/developer/orbs/orb/circleci/path-filtering#orb-source)
- [src/scripts/create-parameters.py](https://github.com/CircleCI-Public/path-filtering-orb/blob/17c4b25958517efdc7476d0adb8e20eb8e823c85/src/scripts/create-parameters.py)
