### ISSUE TITLE
Prevent checkout if you have "persist_to_workspace"

### ISSUE THREAD

**Issue by Alejandroid17** [CircleCI-Public/path-filtering-orb#68]
## Orb version:
circleci/path-filtering@0.1.3

## What happened:
When I try to persist the working environment `persist_to_workspace` and use it, to avoid the `checkout` step, I don't succeed.

```yml
# config.yml

...

jobs:
  # Checkout custom job to only clone the latest changes.
  custom-checkout:
    docker:
      - image: cimg/base:2023.02
    steps:
        ...
      - run:
          name: Clone bitbucket repository
          command: git clone --depth 5 "$CIRCLE_REPOSITORY_URL" --branch "$CIRCLE_BRANCH"
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - project

workflows:

  default-workflow:
    jobs:
      - custom-checkout
      - path-filtering/filter:
          requires:
            - custom-checkout
          name: Filter workflows
          mapping: |
            .*.py test-back true
          base-revision: fast-track
          config-path: .circleci/workflows/default-workflows.yml
          workspace_path: /home/circleci/
```

![image](https://user-images.githubusercontent.com/17381133/219645337-8b0ec829-6403-4138-82d3-b192a0e55a10.png)

## Expected behavior:

Attach workspace and avoid project cloning.

Thanks!! :)
