### ISSUE TITLE
Using $CIRCLE_BRANCH as base-revision

### ISSUE THREAD

**Issue by ciaranmcveigh5** [CircleCI-Public/path-filtering-orb#7]
## Orb version:

 0.0.2

## What happened:

We'd like to be able to pass $CIRCLE_BRANCH to the base-revision parameter in the orb so that the git checks are against it's own branch dynamically. In github the logic is in the python script to check HEAD~1 when the base revision is the same as the current branch. We weren't able to pass $CIRCLE_BRANCH to the base-revision parameter so we tried to override the BASE_REVISION env var which is used in create-parameters.py, again we couldn't find a way to do this with the orb.

`
base = subprocess.run(  ['git', 'merge-base', os.environ.get('BASE_REVISION'), head],  check=True,  capture_output=True).stdout.decode('utf-8').strip()
`

I'm not sure if this is a bug, a missing feature or theres something simple we've missed but having a dynamic base revision opens up lots of possibilities for us and any other teams that aren't doing trunk based development. 

If you could advise us on if there's a work around for this that would be great

Thanks

**Comment by atmosx** [comment]
IMO ` $CIRCLE_BRANCH` should be the default setting. Makes way more sense than `main` or `staging` 🤔

**Comment by benja-M-1** [comment]
I experienced the same behaviour with any environment variable with the following (simplified) code:

```
jobs:
  setup:
    docker:
      - image: cimg/python:3.9.5
    environment: 
      GITHUB_PR_BASE_BRANCH: main # set dynamically by a command
    steps:
      - checkout
      - path-filtering/set-parameters:
          base-revision: $GITHUB_PR_BASE_BRANCH
          mapping: |
            api/.* build-api true
            zoomapp/.* build-zoomapp true
            packages/ui-kit/.* build-packages-ui-kit true
            packages/redux-kit/.* build-packages-redux-kit true
```

When running the set-parameters command base-revision contains the string `$GITHUB_PR_BASE_BRANCH` instead of its value.
