### ISSUE TITLE
`set-parameters` command fails for projects with `.python-version` set

### ISSUE THREAD

**Issue by davware** [CircleCI-Public/path-filtering-orb#70]
## What happened:

When I run the `path-filtering/filter` job in my pipeline, it fails on the `set-parameters` step with this error: `pyenv: version '3.9.9' is not installed (set by /home/circleci/project/.python-version)`. My project has a `.python-version` file which is set to `3.9.9`, which I'm assuming is where the error is coming from when the code is checked out in the `filter` job. I was able to resolve the error by adding `tag: "3.9.9"` to my `filter` job, but I now have to make sure to keep my `.python-version` and `tag` set to the same version, otherwise my setup job will fail. 

## Expected behavior:

It would be nice if the python version in the `filter` job didn't have to match the python version set by my repo's `.python-version`. While it definitely isn't a world ending issue, it's an extra level of coupling that I now have to maintain.

## Additional Information:

my `config.yml` file before changes (build fails): 
```
version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.1.4

workflows:
  setup:
    jobs:
      - path-filtering/filter:
          base-revision: master
          config-path: .circleci/continue_config.yml
          mapping: |
            Dockerfile build-docker-image true
```
screenshot from above build ^: 
![image](https://user-images.githubusercontent.com/120055347/229192425-c7b04566-0ef8-49e0-b41b-084606e17f37.png)

my `config.yml` file after changes (build succeeds): 
```
version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.1.4

workflows:
  setup:
    jobs:
      - path-filtering/filter:
          # this needs to match .python-version
          tag: "3.9.9"
          base-revision: master
          config-path: .circleci/continue_config.yml
          mapping: |
            Dockerfile build-docker-image true
```
