### ISSUE TITLE
continue-config.yml parses 0 prefixed strings in env vars as numbers

### ISSUE THREAD

**Issue by crabsinger** [CircleCI-Public/path-filtering-orb#77]
## Orb version:
```
orbs:
  path-filtering: circleci/path-filtering@0.1.5
```

## What happened:

In a normal Circle CI config.yml I have a workflow like:

```
jobs:
  cypress:
    machine:
      image: ubuntu-2204:2023.02.1
    environment:
      LOCAL_SEED_ADDRESS: '0x21DF875603Ba765a15F9ae20e633D2DAe42952d9'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.18'
      - node/install-packages:
          pkg-manager: yarn
      - run: echo $LOCAL_SEED_ADDRESS
```

This returns the variable as expected.

However, if when I moved this same job file to a continue-config.yml and run it using the path-filtering orb, when it is invoked, I am getting:

![image](https://github.com/CircleCI-Public/path-filtering-orb/assets/83605543/67ef5917-fa87-40ed-ac06-eef0a161bb02)

Which looks like this string is being interpreted as a hex number:

![image](https://github.com/CircleCI-Public/path-filtering-orb/assets/83605543/6334579f-68fd-402b-8add-88df6d0a2fc9)

Example Circle Job where this happened: https://app.circleci.com/pipelines/github/coordinape/coordinape/375/workflows/35b199a6-562f-4b46-a413-f3067e61977b/jobs/979

## Expected behavior:

The expected behavior is that echo'ing this env var should give me back a string of 0x21DF875603Ba765a15F9ae20e633D2DAe42952d9 not a hex number version of that string.

Like it does in the `continue.yml` job here: https://app.circleci.com/pipelines/github/coordinape/coordinape/388/workflows/5fe5261c-3e03-4847-a5b9-0c76aeb55782/jobs/1033
## Additional Information:

Here is a branch with the full config circle ci config files to reproduce this issue: https://github.com/coordinape/coordinape/tree/circle-ci-path-filtering-bug-repro with configs: https://github.com/coordinape/coordinape/tree/circle-ci-path-filtering-bug-repro/.circleci
