### ISSUE TITLE
Generated config remove YAML's aliases

### ISSUE THREAD

**Issue by manh-gntvn** [CircleCI-Public/path-filtering-orb#88]
## Orb version:
1.0.0

## What happened:
In continue YML config file (configured in `path-filtering/filter#config-path` parameter), i use 2 alias in same place (with diff value), after path-filtering/filter job run, generated config only keep last alias.

Its work on `path-filtering` orb v0.1.3

**Example:**

Config file:

```yml
version: 2.1

common:
   parameter_mode: &parameter_mode
    mode:
      type: enum
      enum: ["dev", "prod"]

  parameter_stage: &parameter_stage
    stage:
      type: enum
      enum: ["DEV", "PROD"]

jobs:
  root__deploy:
    parameters:
        <<: *parameter_mode
        <<: *parameter_stage
    executor: node
    steps:
        - ....
```

Generated config file:

```yml
version: 2.1

common:
   parameter_mode: &parameter_mode
    mode:
      type: enum
      enum: ["dev", "prod"]

  parameter_stage: &parameter_stage
    stage:
      type: enum
      enum: ["DEV", "PROD"]

jobs:
  root__deploy:
    parameters:
        <<: *parameter_stage
    executor: node
    steps:
      - ....
```

## Expected behavior:

Keep configured config file as it is

## Additional Information:

CircleCI extension (in VSCode) validate my config is valid.

**Comment by bentastic27** [comment]
@manh-gntvn I worked around this with a config like this:

```
version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@1.0.0
workflows:
  generate-config:
    jobs:
      - explode-yaml
      - path-filtering/filter:
          requires: [explode-yaml]
          base-revision: main
          workspace_path: "/tmp/ymlexplode"
          mapping: |
            somepattern foo bar /tmp/ymlexplode/someconfig.yml
jobs:
  explode-yaml:
    executor:
      name: path-filtering/default
    steps:
    - checkout
    - run:
        name: resolve yaml anchors
        working_directory: .circleci
        command: |
          mkdir /tmp/ymlexplode
          for file in $(find . -type f -name '*.yml'); do yq eval 'explode(.)' $file > /tmp/ymlexplode/$file ; done
    - persist_to_workspace:
        root: '/tmp/ymlexplode'
        paths: ['*.yml']
```
