### ISSUE TITLE
`create_parameters_script` Exception: Expected 3 fields but found 1

### ISSUE THREAD

**Issue by coilysiren** [CircleCI-Public/path-filtering-orb#93]
## Orb version:

`1.0.0`

## CircleCI Config:

```yaml
# docs: https://circleci.com/docs/configuration-reference#version
version: 2.1

# docs: https://circleci.com/docs/using-dynamic-configuration
setup: true

# docs: https://circleci.com/developer/orbs/orb/circleci/path-filtering
orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  monorepo-workflow:
    jobs:
      - path-filtering/filter:
          # syntax:
          #   3-column, whitespace-delimited mapping. One mapping per line
          #   <regex path-to-test> <parameter-to-set> <value-of-pipeline-parameter>
          #
          # description:
          #   when a file changes on a given folder's <path>,
          #   then run the CI workflow for that folder.
          #   the workflows themselves are defined by the `config-path` file.
          # design:
          # changes to infrastructure/ should always trigger infrastructure CI workflows
          # changes to api/ should always trigger api AND infrastructure CI workflows
          # changes to mwaa/ should always trigger mwaa AND infrastructure CI workflows
          # changes to transform/ should always trigger transform CI workflows
          # (not dependent on infrastructure updates)
          # changes to analyze/ should always trigger analyze CI workflows
          # (currently no workflows for this directory, just run tests if available)
          # changes to extract_load_transform/ should always trigger analyze CI workflows
          # (currently no workflows for this directory, just run tests if available)
          mapping: |
            api/.*          run-api-workflow          true
            api/.*          run-infrastructure-workflow          true
            analyze/.*      run-analyze-workflow      true
            extract_load_materialize/.* run-extract-load-materialize-workflow true
            infrastructure/.* run-infrastructure-workflow true
            currently
            mwaa/.*         run-mwaa-workflow         true
            mwaa/.*         run-infrastructure-workflow         true
            transform/.*    run-transform-workflow    true
          name: monorepo-workflow
          base-revision: main
          config-path: .circleci/continue-config.yml
```

## What happened:

```
Collecting pip
  Downloading pip-23.3.1-py3-none-any.whl.metadata (3.5 kB)
Downloading pip-23.3.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 35.3 MB/s eta 0:00:00

Installing collected packages: pip
Successfully installed pip-23.3.1

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: virtualenv in /home/********/.pyenv/versions/3.8.18/lib/python3.8/site-packages (20.24.3)
Requirement already satisfied: distlib<1,>=0.3.7 in /home/********/.pyenv/versions/3.8.18/lib/python3.8/site-packages (from virtualenv) (0.3.7)
Requirement already satisfied: filelock<4,>=3.12.2 in /home/********/.pyenv/versions/3.8.18/lib/python3.8/site-packages (from virtualenv) (3.12.2)
Requirement already satisfied: platformdirs<4,>=3.9.1 in /home/********/.pyenv/versions/3.8.18/lib/python3.8/site-packages (from virtualenv) (3.10.0)
Create python virtual environment for path-filtering
created virtual environment CPython3.10.6.final.0-64 in 899ms
  creator CPython3Posix(dest=/home/********/project/path-filtering-venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/********/.local/share/virtualenv)
    added seed packages: pip==23.2.1, setuptools==68.0.0, wheel==0.41.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
Activate python virtual environment
Creating pipeline parameters
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
Note: switching to '88a3356e86e1fda6b443337a52062a43438f28cf'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 88a3356 update design notes
Comparing 622a410033ef490a129fca33e9c1c5bf12398f3b...88a3356e86e1fda6b443337a52062a43438f28cf
Traceback (most recent call last):
  File "/home/********/project/********_create_parameters_script.py", line 151, in <module>
    create_parameters(
  File "/home/********/project/********_create_parameters_script.py", line 147, in create_parameters
    write_parameters_from_mappings(mappings, changes, output_path, config_path)
  File "/home/********/project/********_create_parameters_script.py", line 71, in write_parameters_from_mappings
    raise Exception("Expected {} fields but found {}".format(element_count, len(m)))
Exception: Expected 3 fields but found 1
```

## Expected behavior:

A path filtering job is successfully created
