### ISSUE TITLE
Path filtering not building when files deleted

### ISSUE THREAD

**Issue by amerodeh-jg** [CircleCI-Public/path-filtering-orb#99]
## Orb version: 

1.0.0

## What happened:
Hi all,
We started using the path filtering orb for one of our pipelines recently.

      - path-filtering/filter:
          name: check-updated-files
          mapping: |
            src/JG.Abc/.*    build-abc    true
            src/JG.Abc.Listener/.* build-abc-listener true
          base-revision: main
          config-path: .circleci/pipeline.yml

We have the above and it has been working fine but today we made a commit that removed 2 files.
```
src/JG.Abc/test.txt
src/JG.Abc.Listener/test.txt
```
And none of the pipelines ran when we pushed it. This feels like a bug?
More context:
A PR had 2 files (.txt) added by mistake. A commit deleted them. Following that commit, no pipeline ran. If our code relied on these 2 files being present and now they’re gone, the build would fail. This feels like a bug.

**Comment by lucas-bsq** [comment]
Witnessed the same behaviour, orb version 1.0.0.

In our case, we deleted some Terraform files, which should have triggered `terraform plan` and/or `terraform apply` jobs to destroy infrastructure. This didn't happen, so we had to add whitespace to some other Terraform file, to trigger the CI.

**Comment by marboledacci** [comment]
I haven't been able to replicate this, validate if the error still happens in latest version of the orb.

**Comment by vishnu-techprescient-teika** [comment]
I am facing same issue with version `2.1.0`. I am trying to sync wiki, and when I delete a file, the continue pipeline does not trigger.
```
version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@2.1.0

workflows:
  version: 2
  check-wiki-changes:
    jobs:
      - path-filtering/filter:
          config-path: .circleci/wiki-workflow.yml
          base-revision: main
          mapping: |
            wiki/.* sync-wiki-workflow true
```
